In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df_genai=pd.read_csv("explanation_prompts_money_laundering.csv")

In [4]:
df_genai.head()

                                  explanation_prompt
0  \n### Instruction:\nAnalyze the transaction de...
1  \n### Instruction:\nAnalyze the transaction de...
2  \n### Instruction:\nAnalyze the transaction de...
3  \n### Instruction:\nAnalyze the transaction de...
4  \n### Instruction:\nAnalyze the transaction de...

In [5]:
df_instructions=pd.read_csv("transactions_with_explanations_v2.csv")

In [6]:
df_instructions.head()

,Time,Sender_account,Receiver_account,Amount,Is_laundering,Laundering_type,Days_Since_Start,Year,Month,Day,Payment_type_Cash Deposit,Payment_type_Cash Withdrawal,Payment_type_Cheque,Payment_type_Credit card,Payment_type_Cross-border,Payment_type_Debit card,Sender_Info,Receiver_Info,explanation_prompt,Model_Explanation
0,60605,7854663749,3790148325,5165.730000,1,Structuring,219,2023,5,14,False,False,False,False,False,True,France - US dollar,India - Dirham,\n### Instruction:\nAnalyze the transaction de...,\n### Instruction:\nAnalyze the transaction de...
1,63383,1423860770,3458503586,3872.390000,1,Structuring,191,2023,4,16,False,False,False,False,False,False,France - US dollar,India - Dirham,\n### Instruction:\nAnalyze the transaction de...,\n### Instruction:\nAnalyze the transaction de...
2,85483,7222999901,71500960,14759.015928,1,Layered_Fan_Out,65,2022,12,11,False,False,False,False,False,False,France - US dollar,India - Dirham,\n### Instruction:\nAnalyze the transaction de...,\n### Instruction:\nAnalyze the transaction de...
3,71203,1872929878,6740948880,4919.010000,1,Structuring,124,2023,2,8,False,False,True,False,False,False,France - US dollar,Germany - Mexican Peso,\n### Instruction:\nAnalyze the transaction de...,\n### Instruction:\nAnalyze the transaction de...
4,44790,685439805,3143116829,7245.670000,1,Stacked Bipartite,49,2022,11,25,False,False,False,False,True,False,France - Turkish lira,Austria - Naira,\n### Instruction:\nAnalyze the transaction de...,\n### Instruction:\nAnalyze the transaction de...

In [7]:
df_instructions.drop('explanation_prompt',axis=1,inplace=True)

In [8]:
df_instructions.head()

,Time,Sender_account,Receiver_account,Amount,Is_laundering,Laundering_type,Days_Since_Start,Year,Month,Day,Payment_type_Cash Deposit,Payment_type_Cash Withdrawal,Payment_type_Cheque,Payment_type_Credit card,Payment_type_Cross-border,Payment_type_Debit card,Sender_Info,Receiver_Info,Model_Explanation
0,60605,7854663749,3790148325,5165.730000,1,Structuring,219,2023,5,14,False,False,False,False,False,True,France - US dollar,India - Dirham,\n### Instruction:\nAnalyze the transaction de...
1,63383,1423860770,3458503586,3872.390000,1,Structuring,191,2023,4,16,False,False,False,False,False,False,France - US dollar,India - Dirham,\n### Instruction:\nAnalyze the transaction de...
2,85483,7222999901,71500960,14759.015928,1,Layered_Fan_Out,65,2022,12,11,False,False,False,False,False,False,France - US dollar,India - Dirham,\n### Instruction:\nAnalyze the transaction de...
3,71203,1872929878,6740948880,4919.010000,1,Structuring,124,2023,2,8,False,False,True,False,False,False,France - US dollar,Germany - Mexican Peso,\n### Instruction:\nAnalyze the transaction de...
4,44790,685439805,3143116829,7245.670000,1,Stacked Bipartite,49,2022,11,25,False,False,False,False,True,False,France - Turkish lira,Austria - Naira,\n### Instruction:\nAnalyze the transaction de...